version: "3.8"

services:
  backend:
    image: soportedev2025/new-backend-demo-003:latest
    container_name: planilla-backend-v2 
    ports:
      - "3200:3005" # Mapeo externo 3200 al interno 3005 corregido
    environment:
      NODE_ENV: production
      PORT: 3005 # Puerto interno corregido
      CORS_ORIGIN: "http://localhost:7080,http://15.235.16.229:7080"
      SQL_SERVER: "15.235.16.229"
      SQL_USER: "sa"
    secrets:
      - SQL_PASSWORD
      - whmcs_identifier
      - whmcs_secret
      - whmcs_api_url
      - mongo_uri_planilla
      - mongo_uri_finance
    networks:
      - backend-planilla-network
      - general_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  frontend:
    image: soportedev2025/new-frontend-demo-005:latest
    container_name: planilla-frontend-v2
    ports:
      - "7080:80" 
    networks:
      - backend-planilla-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  backend-planilla-network:
    external: true
  general_network:
    external: true

secrets:
  SQL_PASSWORD:
    external: true
  whmcs_identifier:
    external: true
  whmcs_secret:
    external: true
  whmcs_api_url:
    external: true
  mongo_uri_planilla:
    external: true
  mongo_uri_finance:
    external: true
